In [54]:
import pandas as pd
from datetime import datetime
import seaborn as sns
from sklearn.cluster import FeatureAgglomeration, AgglomerativeClustering
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [30]:
# Importação dos dados
crime = pd.read_csv('data/KCPD_Crime_Data_2019.csv')

C:\Users\alexa\AppData\Local\Temp\ipykernel_10128\3352860574.py:2: DtypeWarning: Columns (0,9) have mixed types. Specify dtype option on import or set low_memory=False.
  crime = pd.read_csv('data/KCPD_Crime_Data_2019.csv')

# EDA

In [31]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103772 entries, 0 to 103771
Data columns (total 23 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Report_No          103772 non-null  object
 1   Reported_Date      103772 non-null  object
 2   Reported_Time      103772 non-null  object
 3   From_Date          103699 non-null  object
 4   From_Time          103679 non-null  object
 5   To_Date            38513 non-null   object
 6   To_Time            38287 non-null   object
 7   Offense            103772 non-null  object
 8   IBRS               88604 non-null   object
 9   Description        63103 non-null   object
 10  Beat               101968 non-null  object
 11  Address            103753 non-null  object
 12  City               103734 non-null  object
 13  Zip Code           89207 non-null   float64
 14  Rep_Dist           75152 non-null   object
 15  Area               101082 non-null  object
 16  DVFlag             103772 non-null  object
 17  Involvement        103772 non-null  object
 18  Race               90091 non-null   object
 19  Sex                91327 non-null   object
 20  Age                74383 non-null   float64
 21  Firearm Used Flag  103772 non-null  bool
 22  Location           78799 non-null   object
dtypes: bool(1), float64(2), object(20)
memory usage: 17.5+ MB

In [32]:
crime.describe()

           Zip Code           Age
count  89207.000000  74383.000000
mean   64109.252402     37.728621
std     1233.563844     14.142155
min     6114.000000     18.000000
25%    64113.000000     27.000000
50%    64127.000000     35.000000
75%    64133.000000     47.000000
max    99999.000000    353.000000

In [33]:
crime.head()

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,Zip Code,Rep_Dist,Area,DVFlag,Involvement,Race,Sex,Age,Firearm Used Flag,Location
0,KC19044451,06/14/2019,16:34,06/14/2019,16:30,06/14/2019,16:30,Stealing – Shoplift,23C,Shoplifting,...,64114.0,NaN,MPD,N,VIC,NaN,NaN,NaN,False,NaN
1,KC19052276,07/12/2019,22:11,07/13/2019,2:28,NaN,NaN,City/Municipal Warrant Arrest,NaN,NaN,...,NaN,NaN,NaN,N,ARR CHA SUS,W,F,30.0,False,NaN
2,KC19071090,09/17/2019,13:26,09/17/2019,13:15,NaN,NaN,Stealing – Shoplift,23C,Shoplifting,...,64132.0,NaN,MPD,N,VIC,NaN,NaN,NaN,False,NaN
3,KC19073018,09/24/2019,7:32,09/24/2019,7:20,NaN,NaN,Abuse of a Child,13B,Simple Assault,...,64138.0,PJ6509,SPD,Y,SUS,B,M,39.0,False,NaN
4,KC19076088,10/04/2019,13:59,10/04/2019,13:50,NaN,NaN,Recovered Stolen Auto,NaN,NaN,...,NaN,NaN,CPD,N,VIC,NaN,NaN,NaN,False,NaN

In [34]:
crime.tail()

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,Zip Code,Rep_Dist,Area,DVFlag,Involvement,Race,Sex,Age,Firearm Used Flag,Location
103767,190021100,03/22/2019,22:00,03/22/2019,22:00,NaN,NaN,Stealing from Buildi,23D,NaN,...,64110.0,PJ4431,MPD,U,SUS,B,M,18.0,False,NaN
103768,190021380,03/24/2019,8:26,03/23/2019,17:30,03/24/2019,7:45,Property Damage,290,NaN,...,64113.0,PJ4326,MPD,U,VIC,W,M,55.0,False,"30 E 55 ST\r\nKANSAS CITY 64113\r\n(39.027621,..."
103769,190020958,03/22/2019,12:08,03/22/2019,12:08,NaN,NaN,Aggravated Assault (,13A,NaN,...,64134.0,PJ7135,SPD,N,VIC,B,M,61.0,True,7003 E 113 ST\r\nKANSAS CITY 64134\r\n(38.9184...
103770,190021533,03/25/2019,0:13,03/25/2019,0:05,03/25/2019,0:20,Aggravated Assault (,13A,NaN,...,64127.0,PJ0703,EPD,U,VIC,B,F,25.0,True,NaN
103771,190020848,03/22/2019,1:07,03/22/2019,1:07,NaN,NaN,Resisting an Officer,90Z,NaN,...,64124.0,PJ0722,EPD,U,ARR,B,M,27.0,False,4815 INDEPENDENCE AV\r\nKANSAS CITY 64124\r\n(...

In [35]:
crime.sample(10)

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,Zip Code,Rep_Dist,Area,DVFlag,Involvement,Race,Sex,Age,Firearm Used Flag,Location
40214,KC19055548,07/25/2019,0:17,07/24/2019,11:50,07/25/2019,NaN,Burglary (Residential),220,Burglary/Breaking and Entering,...,NaN,PJ4357,MPD,N,SUS,B,F,25.0,False,5400 JACKSON AVE\r\nKANSAS CITY\r\n(39.027525...
1685,KC19025549,04/08/2019,18:26,04/08/2019,18:26,NaN,NaN,Trespass of Real Property,90J,Trespass of Real Property,...,NaN,PJ2114,CPD,N,ARR CHA SUS,W,M,63.0,False,WEST PENNWAY and PENN VALLEY DR\r\nKANSAS CITY...
95425,190007277,01/28/2019,12:45,01/24/2019,0:01,01/26/2019,23:59,Hacking/Computer Inv,26G,NaN,...,64120.0,PJ0206,CPD,U,SUS,U,U,NaN,False,1716 GUINOTTE AV\r\nKANSAS CITY 64120\r\n(39.1...
81305,KC19088623,11/19/2019,16:43,11/19/2019,16:40,11/19/2019,16:43,Domestic Violence Assault (Aggravated),90Z,All Other Offenses,...,64130.0,PJ4649,MPD,Y,ARR VIC SUS CHA,B,M,18.0,False,5800 PARK AVE\r\nKANSAS CITY 64130\r\n(39.021...
58403,KC19083098,10/29/2019,18:02,10/29/2019,9:00,10/29/2019,17:00,Stealing from Auto (Auto Part or Accessory),23G,Theft of Vehicle Parts and Accessories,...,64125.0,NaN,EPD,N,CMP VIC,W,F,28.0,False,5900 INDEPENDENCE AVE\r\nKANSAS CITY 64125\r\...
73850,KC19094911,12/14/2019,13:07,12/14/2019,12:59,NaN,NaN,Stealing – Shoplift,NaN,NaN,...,NaN,PC0387,SCP,N,SUS,W,M,30.0,False,8300 N CHURCH RD\r\nKANSAS CITY\r\n(39.242051...
85075,190011741,02/14/2019,13:58,02/14/2019,13:30,02/14/2019,13:58,Agg Assault - Domest,13A,NaN,...,64130.0,PJ4665,MPD,Y,VIC,B,F,NaN,False,5846 WALROND AV\r\nKANSAS CITY 64130\r\n(39.01...
61027,KC19077285,10/08/2019,16:47,10/08/2019,16:47,NaN,NaN,Miscellaneous City Ordinance Violation,90Z,All Other Offenses,...,64152.0,NaN,NPD,N,VIC,W,F,45.0,False,7000 NW 83RD ST\r\nKANSAS CITY 64152\r\n(39.2...
96075,190017808,03/11/2019,6:30,03/10/2019,15:00,03/11/2019,6:20,Stealing From Auto,23F,NaN,...,64152.0,PP0465,NPD,N,VIC,W,M,52.0,False,7733 N CONANT AV\r\nKANSAS CITY 64152\r\n(39.2...
52225,KC19070882,09/16/2019,23:16,09/16/2019,23:16,NaN,NaN,Possession/Sale/Distribution of a Controlled S...,35A,Drug / Narcotic Violations,...,NaN,PJ4029,MPD,N,INA,B,M,31.0,False,E 51ST ST and SWOPE PKWY\r\nKANSAS CITY\r\n(39...

In [36]:
crime.columns

Index(['Report_No', 'Reported_Date', 'Reported_Time', 'From_Date', 'From_Time',
       'To_Date', 'To_Time', 'Offense', 'IBRS', 'Description', 'Beat',
       'Address', 'City', 'Zip Code', 'Rep_Dist', 'Area', 'DVFlag',
       'Involvement', 'Race', 'Sex', 'Age', 'Firearm Used Flag', 'Location'],
      dtype='object')

In [48]:
crime[crime.duplicated()].sort_index().head()

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,DVFlag,Involvement,Race,Sex,Age,Firearm Used Flag,Location,Reported_Datetime,From_Datetime,To_Datetime
662,KC19081115,10/22/2019,12:55,10/22/2019,12:45,NaN,NaN,Assault (Non-Aggravated),13B,Simple Assault,...,N,SUS,B,M,NaN,False,NaN,2019-10-22 12:55:00,2019-10-22 12:45:00,NaT
1671,KC19030619,04/26/2019,18:59,04/24/2019,8:30,04/24/2019,18:00,Stealing – Other,23H,All Other Larceny,...,N,SUS,W,M,NaN,False,4900 WESTWOOD RD\r\nKANSAS CITY 64112\r\n(39....,2019-04-26 18:59:00,2019-04-24 08:30:00,2019-04-24 18:00:00
1927,KC19032215,05/02/2019,19:06,05/02/2019,19:00,NaN,NaN,Assault (Non-Aggravated),13A,Aggravated Assault,...,N,SUS VIC,W,F,NaN,False,NaN,2019-05-02 19:06:00,2019-05-02 19:00:00,NaT
1942,KC19028723,04/19/2019,21:48,04/19/2019,21:48,04/19/2019,23:53,Assault (Aggravated),13A,Aggravated Assault,...,N,VIC,B,M,NaN,True,E 63RD TRFY and HARDESTY AVE\r\nKANSAS CITY\r\...,2019-04-19 21:48:00,2019-04-19 21:48:00,2019-04-19 23:53:00
2299,KC19022731,03/29/2019,9:32,03/29/2019,9:30,NaN,NaN,Domestic Violence Burglary (Residential),220,Burglary/Breaking and Entering,...,Y,VIC,B,F,NaN,False,5600 NORTON AVE\r\nKANSAS CITY 64130\r\n(39.0...,2019-03-29 09:32:00,2019-03-29 09:30:00,NaT

In [47]:
crime[crime['Age'].isna()].head()

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,DVFlag,Involvement,Race,Sex,Age,Firearm Used Flag,Location,Reported_Datetime,From_Datetime,To_Datetime
0,KC19044451,06/14/2019,16:34,06/14/2019,16:30,06/14/2019,16:30,Stealing – Shoplift,23C,Shoplifting,...,N,VIC,NaN,NaN,NaN,False,NaN,2019-06-14 16:34:00,2019-06-14 16:30:00,2019-06-14 16:30:00
2,KC19071090,09/17/2019,13:26,09/17/2019,13:15,NaN,NaN,Stealing – Shoplift,23C,Shoplifting,...,N,VIC,NaN,NaN,NaN,False,NaN,2019-09-17 13:26:00,2019-09-17 13:15:00,NaT
4,KC19076088,10/04/2019,13:59,10/04/2019,13:50,NaN,NaN,Recovered Stolen Auto,NaN,NaN,...,N,VIC,NaN,NaN,NaN,False,NaN,2019-10-04 13:59:00,2019-10-04 13:50:00,NaT
11,KC19024156,04/03/2019,15:09,04/03/2019,15:00,NaN,NaN,Stealing – Shoplift,23C,Shoplifting,...,N,ARR CHA SUS,B,M,NaN,False,NaN,2019-04-03 15:09:00,2019-04-03 15:00:00,NaT
13,KC19026683,04/12/2019,15:48,02/10/2019,20:22,02/10/2019,20:31,Stealing – Shoplift,23C,Shoplifting,...,N,VIC,NaN,NaN,NaN,False,NaN,2019-04-12 15:48:00,2019-02-10 20:22:00,2019-02-10 20:31:00

In [49]:
crime['Offense'].value_counts()

Offense
Property Damage                               6374
Domestic Violence Assault (Non-Aggravated)    6232
Assault (Aggravated)                          4558
Stolen Auto                                   4504
Stealing – Shoplift                           4435
                                              ...
Casualty (includes a                             1
Attempt Suicide by P                             1
Cold Case Homicide                               1
Tobacco Law Violation                            1
Attempt Suicide by J                             1
Name: count, Length: 221, dtype: int64

In [52]:
crime['Offense'].value_counts().tail(50)

Offense
Impersonation of Another Person            10
False Bomb Report                           9
Animal Cruelty                              8
Pornography                                 8
Animal Abuse/Cruelty                        7
Hacking/Computer Invasion                   7
Extortion/Blackmail                         6
Unlawful Endangerment of Another            6
Tavern/Nightclub Response Report            6
Attempt Suicide by S                        5
Attempt Suicide by O                        5
False ID                                    5
Promoting Prostituti                        5
fraud                                       5
Confiscated Firearm                         5
Kidnapping/Abduction                        5
Curfew Violation                            5
Recovered Missing/Runaway Juvenile          5
Human Trafficking/Commercial Sex Acts       5
Illegal Alien                               4
Hit and Run of a Per                        4
Impersonation - NOT                         4
Human Trafficking/Involuntary Servitude     4
Attempt Suicide by H                        3
Carrying a Concealed Weapon                 3
Adult Entertainment Violation               3
Accidental Drug Over                        3
auto theft                                  3
Attempt Suicide by C                        3
Drunkenness                                 2
Incest                                      2
Sex Off Follow/Entic                        2
Loitering                                   2
5                                           2
Suicide By Shooting                         2
Property Seizure                            2
Sex Off Incest                              2
Outside Correspondence                      2
Suicide By Sleeping                         2
Human Trafficking/Co                        2
misc viol                                   2
Suicide by Other Mea                        1
Gambling - Possessio                        1
Tampering with Physical Evidence            1
Missing/Runaway Juve                        1
Casualty (includes a                        1
Attempt Suicide by P                        1
Cold Case Homicide                          1
Tobacco Law Violation                       1
Attempt Suicide by J                        1
Name: count, dtype: int64

In [50]:
crime[crime['From_Date'].isna()]['Offense'].value_counts().sum()

73

# Data Transformation

## Creating columns

In [43]:
# Data columns
crime['Reported_Datetime'] = pd.to_datetime(crime['Reported_Date'] + ' ' + crime['Reported_Time'], format='%m/%d/%Y %H:%M', errors='coerce')
crime['From_Datetime'] = pd.to_datetime(crime['From_Date'] + ' ' + crime['From_Time'], format='%m/%d/%Y %H:%M', errors='coerce')
crime['To_Datetime'] = pd.to_datetime(crime['To_Date'] + ' ' + crime['To_Time'], format='%m/%d/%Y %H:%M', errors='coerce')
crime['time_until_report'] = crime['Reported_Datetime'] - crime['From_Datetime']

# Binary columns
mask_crime = crime['Age'].isna()
crime.loc[mask_crime, 'is_minor'] = 1
crime.loc[~mask_crime, 'is_minor'] = 0

mask_weekday = crime['From_Datetime'].dt.weekday <= 3
crime.loc[mask_weekday, 'is_weekend'] = 0 
crime.loc[~mask_weekday, 'is_weekend'] = 1

mask_night = (crime['From_Datetime'].dt.time >= pd.to_datetime('18:00:00').time()) | ((crime['From_Datetime'].dt.time <= pd.to_datetime('6:00:00').time()))
crime.loc[mask_night, 'is_night'] = 1
crime.loc[~mask_night, 'is_night'] = 0

# Age columns
mask_minor = crime['Age'].isna()
mask_young_adult = (crime['Age'] >= 18) & (crime['Age'] <= 35)
mask_adult = (crime['Age'] > 35) & (crime['Age'] <= 60)
mask_elder = (crime['Age'] > 60)

crime.loc[mask_minor, 'cat_age'] = 'minor'
crime.loc[mask_young_adult, 'cat_age'] = 'young_adult'
crime.loc[mask_adult, 'cat_age'] = 'adult'
crime.loc[mask_elder, 'cat_age'] = 'mask_elder'

## Dropping data

In [45]:
crime.columns

Index(['Report_No', 'Reported_Date', 'Reported_Time', 'From_Date', 'From_Time',
       'To_Date', 'To_Time', 'Offense', 'IBRS', 'Description', 'Beat',
       'Address', 'City', 'Zip Code', 'Rep_Dist', 'Area', 'DVFlag',
       'Involvement', 'Race', 'Sex', 'Age', 'Firearm Used Flag', 'Location',
       'Reported_Datetime', 'From_Datetime', 'To_Datetime'],
      dtype='object')

In [ ]:
# Deletar tudo que não é Kansas City
mask_kansas_city = crime['City'] != 'KANSAS CITY'
crime = crime.drop(crime[mask_kansas_city].index)

In [5]:
crime = crime.drop(['Reported_Date', 'Reported_Time', 'To_Date', 'To_Time', 'From_Date', 'From_Time', 'Description', 'Beat', 'Address', 'City', 'Zip Code'], axis=1)
crime = crime.drop(crime[crime['Involvement'] != 'VIC'].index)

## Additional EDA

In [53]:
crime[crime['time_until_report'] < pd.to_timedelta(0, 'day')].sort_values(by='time_until_report')

KeyError: 'time_until_report'

# Clusterizing

In [ ]:
cat_vars = ['Offense', 'Rep_Dist', 'Race', 'Sex', 'Firearm Used Flag', 'is_minor', 'is_weekend', 'cat_age', 'is_night']
ohe = OneHotEncoder(drop='first', min_frequency=0.01, handle_unknown='infrequent_if_exist')
preprocessor = ColumnTransformer(transformers=[('onehot', ohe, cat_vars)])
transformed_data = preprocessor.fit_transform(crime)

In [ ]:
ward_2 = AgglomerativeClustering(n_clusters=2, linkage='ward')
crime['label_kmeans'] = ward_2.fit(crime).labels_

ValueError: could not convert string to float: 'KC19044451'

In [ ]:
sns.barplot(x=crime.labels_kmeans.value_counts().index, y=crime.labels_kmeans.value_counts())